### ISSUE TITLE
is page title translated in date format?

### ISSUE THREAD

**Issue by ntap-bmegan** [NetAppDocs/trident-2210.ja-jp#1]
### Page URL

https://docs.netapp.com/ja-jp/trident-2210/index.html

### Page title

Trident 10月22日

### Summary

Compare to other releases. This is what I recall seeing on our PDF cover dates. 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-gudugunti** [comment]
This issue is resolved. Thanks! for reporting it, @ntap-bmegan.
